### ISSUE TITLE
 You should not use <Route> or withRouter() outside a <Router>

### ISSUE THREAD

**Issue by zhangqhzz** [coreui/coreui-free-react-admin-template#176]
"react-router-dom": "^5.0.0"
Uncaught Invariant Violation: You should not use <Route> or withRouter() outside a <Router>
    at invariant (http://192.168.1.72:3000/static/js/9.chunk.js:23304:15)
    at Route.computeMatch (http://192.168.1.72:3000/static/js/10.chunk.js:7393:53)
    at new Route (http://192.168.1.72:3000/static/js/10.chunk.js:7369:20)
    at constructClassInstance (http://192.168.1.72:3000/static/js/9.chunk.js:47700:22)
    at updateClassComponent (http://192.168.1.72:3000/static/js/9.chunk.js:51178:9)
    at beginWork (http://192.168.1.72:3000/static/js/9.chunk.js:52178:20)
    at performUnitOfWork (http://192.168.1.72:3000/static/js/9.chunk.js:56198:16)
    at workLoop (http://192.168.1.72:3000/static/js/9.chunk.js:56239:28)
    at HTMLUnknownElement.callCallback (http://192.168.1.72:3000/static/js/9.chunk.js:36060:18)
    at Object.invokeGuardedCallbackDev (http://192.168.1.72:3000/static/js/9.chunk.js:36109:20)
    at invokeGuardedCallback (http://192.168.1.72:3000/static/js/9.chunk.js:36163:35)
    at replayUnitOfWork (http://192.168.1.72:3000/static/js/9.chunk.js:55422:9)
    at renderRoot (http://192.168.1.72:3000/static/js/9.chunk.js:56352:17)
    at performWorkOnRoot (http://192.168.1.72:3000/static/js/9.chunk.js:57276:11)
    at performWork (http://192.168.1.72:3000/static/js/9.chunk.js:57186:11)
    at performSyncWork (http://192.168.1.72:3000/static/js/9.chunk.js:57160:7)
    at requestWork (http://192.168.1.72:3000/static/js/9.chunk.js:57015:9)
    at scheduleWork (http://192.168.1.72:3000/static/js/9.chunk.js:56828:9)
    at Object.enqueueSetState (http://192.168.1.72:3000/static/js/9.chunk.js:47509:9)
    at DefaultLayout.push../node_modules/react/cjs/react.development.js.Component.setState (http://192.168.1.72:3000/static/js/9.chunk.js:61026:20)
    at http://192.168.1.72:3000/static/js/15.chunk.js:1597:16

The above error occurred in the <Route> component:
    in Route (created by NavLink)
    in NavLink (created by AppSidebarNav)
    in li (created by NavItem)
    in NavItem (created by AppSidebarNav)
    in ul (created by Nav)
    in Nav (created by AppSidebarNav)
    in div (created by ScrollBar)
    in ScrollBar (created by AppSidebarNav)
    in AppSidebarNav (at DefaultLayout.js:284)
    in Suspense (at DefaultLayout.js:283)
    in div (created by AppSidebar)
    in ClickOutComponent (created by AppSidebar)
    in AppSidebar (at DefaultLayout.js:280)
    in div (at DefaultLayout.js:279)
    in div (at DefaultLayout.js:273)
    in DefaultLayout (at App.js:35)
    in Route (at App.js:35)
    in Switch (at App.js:27)
    in Suspense (at App.js:26)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:25)
    in App (at src/index.js:26)

**Comment by zhangqhzz** [comment]
I need to  use "react-router-dom": "^5.0.0"  instead of  "react-router-dom": "~4.3.1"
"in NavLink (created by AppSidebarNav)  "  
Whether NavLink of reactstrap  is available ?
