### ISSUE TITLE
Core UI React is not working in Next JS project

### ISSUE THREAD

**Issue by renetchi** [coreui/coreui-free-react-admin-template#177]
Core UI React is not working in Next JS project, because it has so many `document` and `classList` reference inside the react shared layout. These doesn't work with Server Side Rendering from Next JS.

```
Cannot read property 'classList' of undefined
TypeError: Cannot read property 'classList' of undefined
    at Object.<anonymous> (D:\Documents\GitHub\inviteman\node_modules\@coreui\react\lib\Shared\layout\layout.js:58:41)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Documents\GitHub\inviteman\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Documents\GitHub\inviteman\node_modules\@coreui\react\lib\Sidebar.js:27:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Documents\GitHub\inviteman\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

- Operating system: Windows 10
- Browser and version: Chrome 72

**Comment by zipang** [comment]
This is not the only issue : there is a strong dependency on `react-router-dom` which must be replaced by `next/router`

**Comment by woothu** [comment]
This issue should be resolved in version 3
