### ISSUE TITLE
I have coreUi React on Larave.l but, I have a error eject npm run prod 

### ISSUE THREAD

**Issue by christiantigre** [coreui/coreui-free-react-admin-template#209]
I have integrate template coreUi React js on my project laravel, 

- I eject npm run dev, the project run success.
- I eject npm run watch, the project also run success.
- But, I eject npm run prod, the project show 

On my console.

```
proyecto@0.0.1 prod C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto
> npm run production


> proyecto@0.0.1 production C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

CssSyntaxError: /css/app.css:4022:13: Missed semicolon
    at Input.error (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\input.js:130:16)
    at Parser.checkMissedSemicolon (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\parser.js:603:22)
    at Parser.decl (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\parser.js:286:46)
    at Parser.other (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\parser.js:166:12)
    at Parser.parse (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\parser.js:77:16)
    at parse (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\parse.js:17:12)
    at new LazyResult (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\lazy-result.js:60:16)
    at Processor.<anonymous> (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\processor.js:138:12)
    at Processor.process (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\processor.js:117:23)
    at Function.creator.process (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\postcss\lib\postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\optimize-css-assets-webpack-plugin\src\index.js:73:21)
    at Object.processor (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\optimize-css-assets-webpack-plugin\src\index.js:13:18)
    at C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\last-call-webpack-plugin\src\index.js:150:10
    at arrayEach (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\lodash\_arrayEach.js:15:9)
    at forEach (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\lodash\forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\last-call-webpack-plugin\src\index.js:147:5)
    at C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\last-call-webpack-plugin\src\index.js:178:28
    at _next0 (eval at create (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:17)
    at eval (eval at create (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
    at C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\laravel-mix\node_modules\terser-webpack-plugin\dist\index.js:321:9
    at step (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\laravel-mix\node_modules\terser-webpack-plugin\dist\TaskRunner.js:87:9)
    at C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\laravel-mix\node_modules\terser-webpack-plugin\dist\TaskRunner.js:111:15
    at tryCatcher (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\Users\Administrador\Desktop\desarrollo\bitbucket\toProduction\proyecto\node_modules\bluebird\js\release\promise.js:559:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proyecto@0.0.1 production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the proyecto@0.0.1 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2020-04-04T19_23_23_729Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proyecto@0.0.1 prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the proyecto@0.0.1 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrador\AppData\Roaming\npm-cache\_logs\2020-04-04T19_23_23_750Z-debug.log
```

- My file webpack.mix.js:

```
let mix = require('laravel-mix');
const fs = require('fs');

mix.react('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');  

mix.webpackConfig({ node: { fs: 'empty' }});
```

the error is generated when i add in DefaultLayout the routes

`import routes from "../../routes";`
<AppBreadcrumb appRoutes={routes} />

**Comment by woothu** [comment]
I cannot debug this issue. Lookup laravel integration tutorial: https://www.youtube.com/watch?v=HVVpbpNUJ8M&feature=youtu.be
